INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (66, 'Feu', 8, 'Lion');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (64, 'Air', 6, 'Gémeaux');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (65, 'Eau', 7, 'Cancer');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (61, 'Eau', 3, 'Poisson');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (68, 'Air', 10, 'Balance');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (62, 'Feu', 4, 'Bélier');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (60, 'Air', 2, 'Verseau');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (63, 'Terre', 5, 'Taureau');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (67, 'Terre', 9, 'Vierge');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (59, 'Terre', 1, 'Capricorne');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (69, 'Eau', 11, 'Scorpion');
INSERT INTO SIGNEASTROLOGIQUE (ID, ELEMENT, MOIS, NOM) 
	VALUES (70, 'Feu', 12, 'Sagittaire');
