CREATE TABLE SIGNEASTROLOGIQUE (ID BIGINT NOT NULL, ELEMENT VARCHAR(255), MOIS INTEGER, NOM VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE MEDIUM (ID BIGINT NOT NULL, BIOGRAPHIE VARCHAR(255), NOM VARCHAR(255), TALENT VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE EMPLOYE (ID BIGINT NOT NULL, EMAIL VARCHAR(255), LOGIN VARCHAR(255), MOTDEPASSE VARCHAR(255), NOM VARCHAR(255), PRENOM VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE PREDICTION (NUMERO BIGINT NOT NULL, DTYPE VARCHAR(31), NIVEAU INTEGER, TEXTE VARCHAR(255), PARTENAIRE_ID BIGINT, CONSEIL VARCHAR(255), PRIMARY KEY (NUMERO));

